[package]
edition = "2021"
name = "rhythmic"
version = "0.1.0"
authors = ["Michael Kerscher <rust@kerscher-michael.de>"]
description = "Maintain consistent timing with configurable overrun behavior."
license = "MIT OR Apache-2.0"

[dependencies]
